<?php

namespace Gravita\SyliusNotifyWhenAvailablePlugin\Repository;

/**
 * NotificationListItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationListItemRepository extends \Doctrine\ORM\EntityRepository
{
}
