<?php

namespace Titi60\SyliusNotifyWhenAvailablePlugin\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * NotificationListItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationListItemRepository extends EntityRepository
{
}
