<?php

namespace Gravita\SyliusNotifyWhenAvailablePlugin\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductVariantTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVariantTranslationRepository extends EntityRepository
{
}
