imports:
    - { resource: '@GravitaSyliusNotifyWhenAvailablePlugin/Resources/config/grids.yml' }

sylius_product:
    resources:
        product_variant:
            classes:
                model: Titi60\SyliusNotifyWhenAvailablePlugin\Entity\ProductVariant
            translation:
                classes:
                    model: Titi60\SyliusNotifyWhenAvailablePlugin\Entity\ProductVariantTranslation