sylius_resource:
    resources:
        gravita.notification_list:
            driver: doctrine/orm
            classes:
                model: Titi60\SyliusNotifyWhenAvailablePlugin\Entity\NotificationList
        gravita.notification_list_item:
            driver: doctrine/orm
            classes:
                model: Titi60\SyliusNotifyWhenAvailablePlugin\Entity\NotificationListItem