Titi60\SyliusNotifyWhenAvailablePlugin\Entity\NotificationList:
    type: entity
    table: gravita_notification_list
    repositoryClass: Titi60\SyliusNotifyWhenAvailablePlugin\Repository\NotificationListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        productVariant:
            targetEntity: Titi60\SyliusNotifyWhenAvailablePlugin\Entity\ProductVariant
            inversedBy: notificationList
            joinColumn:
                name: product_variant_id
                referencedColumnName: id
    oneToMany:
        items:
            targetEntity: Titi60\SyliusNotifyWhenAvailablePlugin\Entity\NotificationListItem
            mappedBy: notificationList
            cascade:
                - persist
                - refresh
    lifecycleCallbacks: {  }
